<?xml version="1.0" encoding="utf-8"?>
<definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://tsfactoriesws.cgg.gov.in/" name="TSFactoryServiceImplService" targetNamespace="http://tsfactoriesws.cgg.gov.in/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema>
      <xsd:import schemaLocation="http://test.cgg.gov.in:8082/tsFactoriesAnnualLicenseFeeWS/tsFactoriesWebServiceAnnualLicenseFee?xsd=1" namespace="http://tsfactoriesws.cgg.gov.in/" />
    </xsd:schema>
  </types>
  <message name="insertFactoryAnnualLicenseFeeDetails">
    <part name="parameters" element="tns:insertFactoryAnnualLicenseFeeDetails" />
  </message>
  <message name="insertFactoryAnnualLicenseFeeDetailsResponse">
    <part name="parameters" element="tns:insertFactoryAnnualLicenseFeeDetailsResponse" />
  </message>
  <message name="isValidFactoryRegistrationNumber">
    <part name="parameters" element="tns:isValidFactoryRegistrationNumber" />
  </message>
  <message name="isValidFactoryRegistrationNumberResponse">
    <part name="parameters" element="tns:isValidFactoryRegistrationNumberResponse" />
  </message>
  <portType name="TSFactoryService">
    <operation name="insertFactoryAnnualLicenseFeeDetails">
      <input message="tns:insertFactoryAnnualLicenseFeeDetails" />
      <output message="tns:insertFactoryAnnualLicenseFeeDetailsResponse" />
    </operation>
    <operation name="isValidFactoryRegistrationNumber">
      <input message="tns:isValidFactoryRegistrationNumber" />
      <output message="tns:isValidFactoryRegistrationNumberResponse" />
    </operation>
  </portType>
  <binding name="TSFactoryServiceImplPortBinding" type="tns:TSFactoryService">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <operation name="insertFactoryAnnualLicenseFeeDetails">
      <soap:operation soapAction="" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
    <operation name="isValidFactoryRegistrationNumber">
      <soap:operation soapAction="" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
  </binding>
  <service name="TSFactoryServiceImplService">
    <port name="TSFactoryServiceImplPort" binding="tns:TSFactoryServiceImplPortBinding">
      <soap:address location="http://test.cgg.gov.in:8082/tsFactoriesAnnualLicenseFeeWS/tsFactoriesWebServiceAnnualLicenseFee" />
    </port>
  </service>
</definitions>